name: Hieu M. Nguyen
slogan: I build softwares.
highlighter: rouge 
paginate: 5 # number of posts per page
url: http://ngnmhieu.com

# social networks link
github: https://github.com/ngnmhieu
twitter: http://twitter.com/ngnmhieu
googleplus: https://plus.google.com/+HieuNguyenMinh0101
linkedin: http://linkedin.com/in/ngnmhieu
xing: https://www.xing.com/profile/HieuM_Nguyen

cv_de: "/files/cv_hieu_nguyen_de.pdf"
cv_en: "/files/cv_hieu_nguyen_en.pdf"
